#!/bin/bash
#Check if OIPA_auth is currently installed
INSTALLED=$(pip freeze |grep OIPA_auth|wc -l)
if [ $INSTALLED -eq 1 ]
then
    echo "Y" | pip uninstall OIPA_auth
fi

#Install OIPA_auth
pip install -e .
